config/routes.rb
Rails.application.routes.draw do
  root 'schedules#index'
  resources :schedules
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  validates :title, presence: true, length: { maximum: 20 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date
  validates :memo, length: { maximum: 500 }

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "must be after the start date")
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  def index
    @schedules = Schedule.all
  end

  def show
  end

  def new
    @schedule = Schedule.new
  end

  def edit
  end

  def create
    @schedule = Schedule.new(schedule_params)
  
    if @schedule.save
      flash[:notice] = 'Schedule was successfully created.'
      redirect_to @schedule
    else
      render :new
    end
  end
  
  def update
    if @schedule.update(schedule_params)
      flash[:notice] = 'Schedule was successfully updated.'
      redirect_to @schedule
    else
      render :edit
    end
  end
  

  def destroy
    @schedule.destroy
    redirect_to schedules_url, notice: 'Schedule was successfully destroyed.'
  end

  private
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    def schedule_params
      params.require(:schedule).permit(:title, :start_date, :end_date, :memo, :all_day)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
      <% unless message_type.to_s == 'notice' %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <% end %>
  
    <%= yield %>
  </body>
</html>

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true, data: { turbo: false }) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
    <% if schedule.errors.include?(:title) %>
      <div class="error"><%= schedule.errors.full_messages_for(:title).join(", ") %></div>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>

  <div class="field">
    <%= form.label :all_day %>
    <%= form.check_box :all_day %>
  </div>

  <div class="field">
    <%= form.label :memo %>
    <%= form.text_area :memo, size: "60x12" %>
    <% if schedule.errors.include?(:memo) %>
      <div class="error"><%= schedule.errors.full_messages_for(:memo).join(", ") %></div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/schedules/edit.html.erb
<h1>Edit Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>タイトル</th>
      <th>開始日</th>
      <th>終了日</th>
      <th>終日</th>
      <th>メモ</th>
      <th>更新日時</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <p>Today: <%= Date.today.strftime('%Y/%m/%d') %></p>
    <p>Total: <%= @schedules.count %></p>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.id %></td>
        <td><%= schedule.title %></td>
        <td><%= schedule.start_date.strftime('%Y/%m/%d') %></td>
        <td><%= schedule.end_date.strftime('%Y/%m/%d') %></td>
        <td><%= schedule.all_day ? '○' : '' %></td>
        <td><%= schedule.memo %></td>
        <td><%= schedule.updated_at.strftime('%Y/%m/%d %H:%M') %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= button_to 'Destroy', schedule, method: :delete, data: { controller: "confirm", action: "confirm#confirm" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @schedule.title %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @schedule.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @schedule.end_date %>
</p>

<p>
  <strong>All day:</strong>
  <%= @schedule.all_day ? '○' : '' %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>